### ISSUE TITLE
DBConnection.Holder.checkout(#PID<0.X.X>, [timeout: 15000 ])

### ISSUE THREAD

**Issue by sudoish** [florinpatrascu/bolt_sips#116]
## Environment

* Elixir version 1.16.3
* neo4j:5.20.0
* Connection scheme (`bolt://`, `bolt+routing://` or `neo4j://`):
* Bolt.Sips version 2.0.11:
* Operating system: Mac Osx and Ubuntu 20

## Current behavior

I am getting the following error when trying to perform a simple query:

```
DBConnection.Holder.checkout(#PID<0.X.X>, [timeout: 15000 ])
```

Is this because of a non-supported version or could it be a misconfiguration on my end?
Thanks in advance!

## Here is the config I am using:

```ex
config :bolt_sips, Bolt,
  url: "bolt://localhost:7687",
  basic_auth: [username: "neo4j", password: "testtest"],
  pool_size: 10
```

## And here is the test case:

```ex
  test "Test query works" do
    conn = Bolt.Sips.conn()
    query = "MATCH (n) RETURN n"
    result = Bolt.Sips.query!(conn, query)
  end
```

## Dockerfile with the neo4j config:

```yaml
services:
  neo4j:
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=neo4j/testtest
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

```
